export * from './listsActions';

export const CONSTANTS = {
  ADD_CARD: 'ADD_CARD',
  EDIT_CARD: 'EDIT_CARD',
  DELETE_CARD: 'DELETE_CARD',
  TOGGLE_CARD: 'TOGGLE_CARD',
  ADD_LIST: 'ADD_LIST',
  EDIT_LIST: 'EDIT_LIST',
  DRAG_HAPPENED: 'DRAG_HAPPENED',
  TOGGLE_THEME: 'TOGGLE_THEME',
};
